name = "launch-darkly-otel-issue"
main = "src/worker.ts"
compatibility_date = "2023-08-21"
compatibility_flags = [ "nodejs_compat" ]

[vars]
LAUNCH_DARKLY_CLIENT_ID = "444444444444444444444444"

[[kv_namespaces]]
binding = "LAUNCH_DARKLY_KV"
id = "aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa"
preview_id = "bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb"
